# Generated by Django 4.2.7 on 2025-12-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_advance',
            field=models.BooleanField(default=False),
        ),
    ]
