# Generated by Django 4.2.7 on 2025-12-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_customer_alter_payment_amount_and_more'),
    ]

    operations = [
    ]
