# Generated by Django 4.2.7 on 2025-12-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_make_customer_non_nullable'),
    ]

    operations = [
    ]
