# Generated by Django 4.2.7 on 2025-12-12 08:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_total_amount_and_more'),
        ('customers', '0001_initial'),
        ('payments', '0006_alter_payment_amount_alter_payment_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(help_text='Customer who made / received this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Optional: link payment to a specific invoice (legacy support).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice'),
        ),
    ]
