# Generated by Django 5.2.9 on 2025-12-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceitem_discount_type_invoiceitem_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
