# Generated by Django 5.2.9 on 2025-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
